name: Build and Deploy Java Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Adjust the Java version as needed

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: your-heroku-app-name # Replace with your Heroku app name
          heroku_email: your-email@example.com # Replace with your Heroku email address
